---
- name: Cleanup Test Files
  hosts: all
  connection: local
  gather_facts: false
  tasks:
    - name: Ensure Vagrantfile not present
      ansible.builtin.file:
        path: "{{ molecule_ephemeral_directory }}/Vagrantfile"
        state: absent
    - name: Remove Dummy File
      ansible.builtin.file:
        path: "{{ molecule_ephemeral_directory }}/dummy.txt"
        state: absent
