---
- name: Trial Vagrantfile Role
  hosts: all
  connection: local
  gather_facts: false
  vars:
    vagrantfile_location: "{{ molecule_ephemeral_directory }}"
    vagrantfile_virtual_machines:
      - label: test_1
        box: rockylinux/9
        provider:
          virtualbox:
            cpus: 1
            memory: 1024
            name: Test-VM-1
        provision:
          ansible:
            groups:
              - test
            playbook: playbook.yml
        network:
          forwarded_ports:
            - host: 8080
              guest: 80
            - host: 4443
              guest: 443
      - label: test_2
        box: rockylinux/9
        provider:
          libvirt:
            cpus: 2
            memory: 2048
            video_type: virtio
        network:
          private_network:
            type: dhcp
        provision:
          shell: |
            echo "Setting up machine..."
            dnf install -y httpd
            systemctl enable --now httpd
          ansible:
            groups:
              - production
            playbook: playbook.yml
      - label: test_3
        box: rockylinux/9
        provider:
          virtualbox:
            name: Test-VM-3
        provision:
          files:
            - src: dummy.txt
              dest: /usr/bin/dummy
  roles:
    - zarethrex.vagrantfile
