---
- name: Trial Vagrantfile Role
  hosts: all
  connection: local
  gather_facts: false
  vars:
    vagrantfile_location: "{{ molecule_ephemeral_directory }}"
    vagrantfile_virtual_machines:
      - label: test_1
        name: Test-VM-1
        box: rockylinux/9
        provider: virtualbox
        cpus: 1
        memory: 1024
        provision:
          ansible:
            groups:
              - test
            playbook: playbook.yml
      - label: test_2
        name: Test-VM-2
        box: rockylinux/9
        provider: virtualbox
        cpus: 2
        memory: 2048
        provision:
          shell: |
            echo "Setting up machine..."
            dnf install -y httpd
            systemctl enable --now httpd
          ansible:
            groups:
              - production
            playbook: playbook.yml
  roles:
    - zarethrex.vagrantfile
