---
- name: Verify
  hosts: all
  connection: local
  gather_facts: false
  tasks:
    - name: Perform Checks
      block:
        - name: Validate Vagrantfile
          ansible.builtin.command:
            cmd: vagrant validate --no-provider --no-tty
            chdir: "{{ molecule_ephemeral_directory }}"
            creates: "{{ molecule_ephemeral_directory }}/validate.log"
          register: validation
      rescue:
        - name: Show Vagrantfile
          failed_when: validation.rc != 0
          ansible.builtin.debug:
            msg: "{{ lookup('file', molecule_ephemeral_directory ~ '/Vagrantfile') }}"
